### PR TITLE
[frontend] Fix spacing for tags (#1112)

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Space for tags, add tooltips, and name with remaining tags :
* Add tooltips, chip with number of remaining tags
image
image
image

### Related issues

* bug/1112
*

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Dimfacion — DISMISSED** [review]

**Comment by Dimfacion** [comment]
Nitpick : I think we need a team chat about the naming because there are bugfix/xxx, bug/xxx and issue/xxx branches that all are supposed to fix bugs.

**Review by Christian-DONGMO — CHANGES_REQUESTED** [review]
It seems that it doesn't work correctly on simulations. In fact when I have a simulation with more than two tags, I don't see the tag with the remains number of tags

**Comment by savacano28** [comment]
@Christian-DONGMO I see. What was your resolution?

**Comment by Christian-DONGMO** [comment]
This is my screen settings : 

image

**Review by Christian-DONGMO — APPROVED** [review]
It works fine now.

**Pull request merged**
