### PR TITLE
[frontend] adding import button on exercises list page

### PR DESCRIPTION
**Pull request by Christian-DONGMO**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by guillaumejparis** [comment]
Please align style on scenarios one : 
image
image

**Comment by Christian-DONGMO** [comment]
Style aligned

**Comment by guillaumejparis** [comment]
Please use a ToggleButtonGroup

**Comment by Christian-DONGMO** [comment]
It's done!

**Review by RomuDeuxfois — APPROVED** [review]

**Review by guillaumejparis — APPROVED** [review]

**Pull request merged**
