### PR TITLE
[docker] clean up temporary apt list files in Dockerfiles

### PR DESCRIPTION
**Pull request by PeterDaveHello**
### Proposed changes

* clean up temporary apt list files in Dockerfiles

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Dimfacion** [comment]
Hi @PeterDaveHello !
Thank you for the pull request! 🎉 We're excited to see your contribution to the project. We'll review it and get back to you soon with any feedback. If you have any questions in the meantime, feel free to ask!
Openbas Team - Filigran

**Comment by Dimfacion** [comment]
Hi again ! 
Could you please sign your commits ?
Thanks :)

**Comment by PeterDaveHello** [comment]
Should be done now, thanks.

**Review by guillaumejparis — APPROVED** [review]

**Comment by guillaumejparis** [comment]
Hello @PeterDaveHello unfortunately your commit is still not signed, not sure why as I see the signed off message on your commit but no "verified" tag, maybe see https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by PeterDaveHello** [comment]
Hi @Guillaume, I’ve added a Signed-off-by, but I haven’t set up a GPG key due to convenience. Given that this is a small change and the commit is still traceable, is it possible to move forward without the verified tag for this PR? Thanks!

**Comment by guillaumejparis** [comment]
Yes I understand but even maintainers cannot merge on the repository without signed commit if you want I can close this PR in favor of this one with your commit cherry pick and signed by me : https://github.com/OpenBAS-Platform/openbas/pull/1736

**Comment by PeterDaveHello** [comment]
It seems the rules are quite strict, but I'll try to handle this issue.

**Comment by guillaumejparis** [comment]
@PeterDaveHello Hello, did you have some time to try ?

**Comment by PeterDaveHello** [comment]
Let me try it at the weekend!

**Comment by RomuDeuxfois** [comment]
Hi,

We have added your code here: https://github.com/OpenBAS-Platform/openbas/commit/51d7d27ab2266a20614dd6356cc46c2b89ff0426

So, we are closing this PR.

Many thanks for your work and sorry for handling it.

**Pull request closed without merging**
